
twilio:
  account_sid: AC6277d4bb7daa1a3f784d7eae63cc4ece
  auth_token: be2525e9968419fdddbd7eda165db2cd
  trial_number: +15706832019


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/healthMate
    password: ala
    username: ala
  application:
    name: healthMate
  mail:
    host: smtp.gmail.com
    port: 587
    username: bjaouiala3@gmail.com
    password: "txyr dwts ojkp qkrb"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.debug: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000
      mail.smtp.trust: smtp.gmail.com

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 500MB

application:
  security:
    jwt:
      secret-key: yhwdxGYjqMr3qRBFFxF3l7si5Q9PfetGI1TD0t4sl06ksSdvyhgLss8YL066tJsZ
      expiration : 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  servlet:
    context-path: /api/v1
  port: 8094
