package com.healthmate.healthmate.HealthIndice;

import com.healthmate.healthmate.user.User;
import com.healthmate.healthmate.user.UserRepository;
import jakarta.persistence.EntityNotFoundException;
import jakarta.transaction.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class HealthIndiceService {
    @Autowired
    private HealthIndiceRepository healthIndiceRepository;
    @Autowired
    private UserRepository userRepository ;

    // Get all health indices for a specific user
    public List<HealthIndice> getAllHealthIndicesByUser(Long userId) {
        return healthIndiceRepository.findByUserId(userId); // Fetch indices for the specific user
    }

    // Get a single health indice by its ID
    public HealthIndice getHealthIndiceById(Long id) {
        return healthIndiceRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Health Indice not found with id: " + id));
    }

    @Transactional
    public HealthIndice createHealthIndice(HealthIndice healthIndice, Long userId) {
        User user = userRepository.findById(userId)
                .orElseThrow(() -> new EntityNotFoundException("User not found with id: " + userId));

        healthIndice.setUser(user);  // Associate the health index with the user

        // Save the health index; ID will be auto-generated by the database
        return healthIndiceRepository.save(healthIndice);
    }


    // Update an existing health indice
    public HealthIndice updateHealthIndice(Long id, HealthIndice healthIndiceDetails) {
        HealthIndice healthIndice = getHealthIndiceById(id);

        // Update fields based on healthIndiceDetails
        healthIndice.setAge(healthIndiceDetails.getAge());
        healthIndice.setSystolicBP(healthIndiceDetails.getSystolicBP());
        healthIndice.setDiastolicBP(healthIndiceDetails.getDiastolicBP());
        healthIndice.setBs(healthIndiceDetails.getBs());
        healthIndice.setBodyTemp(healthIndiceDetails.getBodyTemp());
        healthIndice.setHeartRate(healthIndiceDetails.getHeartRate());

        return healthIndiceRepository.save(healthIndice);
    }

    // Delete a health indice by ID
    public void deleteHealthIndice(Long id) {
        HealthIndice healthIndice = getHealthIndiceById(id);
        healthIndiceRepository.delete(healthIndice);
    }
}
